- name: "Install PostgreSQL and relate packages"
  include_role:
    name: 3trains_fastpackages

- set_fact:
    pgdata: "{{ lookup('env','PGDATA') | default('/var/lib/pgsql/data') }}"

- name: "Init PostgesQL Db"
  command:
    cmd: /usr/bin/postgresql-setup initdb
    creates: /var/lib/pgsql/initdb.log
  register: datadir_init

- name: "Ensure PostgreSQL accept connection with password"
  template:
    src: pg_hba.conf
    dest: /var/lib/pgsql/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600

- name: "Ensure the PostgreSQL service is running"
  service:
    name: postgresql
    state: started
    enabled: yes
  when: datadir_init is success

- name: "Create database {{ db.name }}"
  become: true
  postgresql_db:
    name: "{{ db.name }}"
    encoding: UTF-8
    template: 'template0'

- name: "Create user for database"
  become: true
  postgresql_user:
    db: "{{ db.name }}"
    name: "{{ db.user }}"
    password: "{{ db.user }}"
    priv: ALL
    state: present
