---

- name: "Enable Keycloak if requested"
  include_tasks: keycloak.yml

- name: "Enable HTTS if requested"
  include_tasks: https.yml

- name: "Fine tune Wildfly configuration"
  jcliff:
    wfly_home: "{{ wildfly.home }}"
    management_port: "{{ 9990 + ((item - 1) * 100) }}"
    subsystems:
      - system_props:
          - name: jcliff.enabled
            value: 'enabled.plus'
      - deployments:
          - name: "{{ app_dest | basename }}"
            path: "{{ app_dest }}"
            replace_name_regex: "{{  (app_dest | basename).split('-')[0] }}-.*"
      - drivers:
          - driver_name: postgresql
            driver_module_name: org.postgresql
            driver_class_name: org.postgresql.Driver
            driver_xa_datasource_class_name: org.postgresql.xa.PGXADataSource
      - datasources:
          - name: "{{ wildfly.config_name_prefix }}db"
            use_java_context: 'true'
            jndi_name: "java:jboss/datasources/{{ wildfly.config_name_prefix }}db"
            connection_url: "jdbc:postgresql://localhost:5432/{{ wildfly.config_name_prefix }}db"
            driver_name: postgresql
            user_name: "{{ wildfly.user }}"
            password: "{{ wildfly.user }}"
      - keycloak:
          - secure_deployment:
              - deployment_name: "{{ app_detail.name + '.' + app_detail.extension }}"
                realm: "{{ keycloak_realm }}"
                auth_server_url: "{{ keycloak_url }}/auth/"
                ssl_required: EXTERNAL
                resource: "{{ keycloak_client }}"
                credential: "{{ keycloak_client_secret_response.json.value }}"
                verify_token_audience: true
                use_resource_role_mappings: true
  when: wildfly.enable.subsys_config
