---

- name: "Ensures required packages are installed"
  yum:
    name:
      - zip
      - unzip
      - gcc
      - redhat-rpm-config
      - procps-ng
      - python3-pip
      - python3-devel
      - initscripts
      - "{{ jvm_package | default('java-1.8.0-openjdk-devel') }}"
    state: present

- name: "Copy Rules Directory"
  copy:
    src: "files/rules/"
    dest: "{{ jcliff_rules_dir }}"

- name: "Lookup Rules file"
  slurp:
    src: "{{ jcliff_rules_dir }}/rules"
  register: rules_file

- name: "Get last line of rules file"
  set_fact:
    rules_file_last_line: "{{ (rules_file['content'] | b64decode).splitlines()[-1] }}"

- name: Append keycloak rule to jcliff rules file
  lineinfile:
    path: "{{ jcliff_rules_dir }}/rules"
    regex: "^configurable*keycloak"
    line: "{{ 'configurable.'+(((rules_file_last_line.split('=')[0].split('.')[1] | int)+1)|string) + '=keycloak' }}"
  when: rules_file_last_line.split('=')[1] != 'keycloak'
