---
- name: Playbook for Keycloak Hosts
  hosts: keycloak
  tasks:
    - name: Keycloak Role
      include_role:
        name: 3trains_keycloak
      vars:
        trains_app_host: "{{ (groups['wildfly'][0]) if groups['wildfly']| length > 0 else 'localhost' }}"
