---
- name: Playbook for Postgresql Setup
  hosts: wildfly
  tasks:
    - name: Wildfly Role
      include_role:
        name: 3trains_postgresql
        #      vars:
        #keycloak_3trains_url: "{{ 'http://' + (groups['keycloak'][0] if groups['keycloak']| length > 0 else 'localhost')  + ':8080' }}"
