---
- name: Playbook to validate host met the preconditions
  hosts: wildfly
  tasks:

    - assert:
        that:
          - ansible_distribution is defined
          - ansible_distribution == "RedHat"
          - ansible_distribution_version is defined
          - ansible_distribution_version == "8.4"
          - ansible_version is defined
          - ansible_version.string is version('2.9','>')
          - ansible_python_version is defined
          - ansible_python_version is version('3.6','>')
        quiet: true
        fail_msg: "This demo has been built for RHEL 8.4 using Ansible 2.9 running on Python 3"
